### ISSUE TITLE
cheerio issue

### ISSUE THREAD

**Issue by martinlejko** [iconify/tools#41]
Hi. When using cheerio and iconify i get this. I am using github actions, and the way I think it works it does pnpm install and astro check. If I do that on local / github action I get this issue that I provided. Althout I can fix it if i rewrite the import `import * as cheerio from 'cheerio';` it works.

`Error when evaluating SSR module /Users/martinlejko/Repos/github.com/martinlejko/martinlejko.github.io/astro.config.ts: failed to import "astro-icon"
|- file:///Users/martinlejko/Repos/github.com/martinlejko/martinlejko.github.io/node_modules/.pnpm/@iconify+tools@3.0.7/node_modules/@iconify/tools/lib/svg/index.mjs:1
import cheerio from 'cheerio';
       ^^^^^^^
SyntaxError: The requested module 'cheerio' does not provide an export named 'default'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:171:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:254:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:474:24)
    at async nodeImport (file:///Users/martinlejko/Repos/github.com/martinlejko/martinlejko.github.io/node_modules/.pnpm/vite@5.4.0_@types+node@22.2.0/node_modules/vite/dist/node/chunks/dep-NjL7WTE1.js:52928:15)
    at async ssrImport (file:///Users/martinlejko/Repos/github.com/martinlejko/martinlejko.github.io/node_modules/.pnpm/vite@5.4.0_@types+node@22.2.0/node_modules/vite/dist/node/chunks/dep-NjL7WTE1.js:52786:16)
    at async eval (/Users/martinlejko/Repos/github.com/martinlejko/martinlejko.github.io/astro.config.ts:9:31)
    at async instantiateModule (file:///Users/martinlejko/Repos/github.com/martinlejko/martinlejko.github.io/node_modules/.pnpm/vite@5.4.0_@types+node@22.2.0/node_modules/vite/dist/node/chunks/dep-NjL7WTE1.js:52844:5)`
    
    Is there a way that we change the import line into the compatible one?

**Comment by cyberalien** [comment]
Update `@iconify/tools` package to latest version, it has a workaround for cheerio bug.

**Comment by martinlejko** [comment]
Maybe I am doing something wrong, but when I `pnpm update @iconify/tools` or even check it in `packages.json` it is the correct version of `^4.0.5`. Removed the `node_modules` and `pnpm install` without doing anything else it crashes on the same cherio error. I am sorry if I am doing something wrong on my part.

**Comment by cyberalien** [comment]
Few things to check:
- Make sure cheerio version is 1.0.0, not older
- Run `pnpm dedupe`

**Comment by cyberalien** [comment]
I looked at issue again and noticed that error shows `@iconify+tools@3.0.7`, so I guess Astro Icon is using version 3.0.7.

That version has `"cheerio": "^1.0.0-rc.12"` in dependencies, which also matches `1.0.0` released 2 days ago that broke types. Maybe you can patch it to `"cheerio": "1.0.0-rc.12"` (remove `^`) to force older version.
